name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master, main, /^\d+\.\d+\.\d+$/]
  pull_request:
    branches: [master, main, /^\d+\.\d+\.\d+$/]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-command: [
            "pnpm jest jest",
            "pnpm vitest vitest",
            "pnpm vitest vitest --pool=threads",
            "pnpm vitest vitest --pool=forks",
            "pnpm vitest vitest --pool=vmThreads",
            "pnpm test:js"
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
      - run: pnpm install
      - run: ${{ matrix.test-command }}
